name: CMake on a single platform

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  BUILD_TYPE: Release
  CC: gcc-14
  CXX: g++-14
  OPAL_PREFIX: /opt/hpcx/ompi

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Enable the proposed repository
      uses: myci-actions/add-deb-repo@11
      with:
	repo: deb http://archive.ubuntu.com/ubuntu 24.04-proposed main restricted universe multiverse

    - name: Install libomp
      run: sudo apt-get update; sudo apt-get install -t -y openmpi-bin libopenmpi-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tests

